import pandas as pd

# Define columns
columns = [
    'Question', 'Question Type', 'Answer Option 1', 'Explanation 1', 
    'Answer Option 2', 'Explanation 2', 'Answer Option 3', 'Explanation 3', 
    'Answer Option 4', 'Explanation 4', 'Answer Option 5', 'Explanation 5', 
    'Answer Option 6', 'Explanation 6', 'Correct Answers', 'Overall Explanation', 'Domain'
]

# Helper to normalize each row to exactly 17 columns
def normalize_row(row):
    # Keep only the first 2 elements (Question, Type)
    base = row[:2]
    
    # Extract answers and explanations
    answers = row[2:-3]  # everything except Question, Type, Correct, Overall Explanation, Domain
    correct_answers = row[-3]
    overall_explanation = row[-2]
    domain = row[-1]
    
    # Pad answers/explanations to 6 pairs
    while len(answers) < 12:
        answers.append(None)
    
    # Trim answers if somehow longer than 12
    answers = answers[:12]
    
    # Combine everything
    return base + answers + [correct_answers, overall_explanation, domain]

# The 65 Questions Data
data = [
    ['A company runs a web app on EC2 with unpredictable traffic spikes. What is the most cost-effective and scalable solution?', 'multiple-choice', 'Use a scheduled scaling policy', 'Scheduled scaling is for predictable traffic only.', 'Manually add more instances', 'This is not scalable and is prone to error.', 'Use a dynamic scaling policy based on CPU utilization', 'This automatically scales based on real-time demand.', 'Over-provision a large number of instances', 'This is not cost-effective.', None, None, None, None, '3', 'A dynamic Auto Scaling policy adjusts the number of EC2 instances automatically in response to changes in demand ensuring performance while minimizing cost.', 'Design High-Performing Architectures'],
    ['An organization needs to store 7 years of audit logs. The logs are rarely accessed after the first month but must be retrievable within 24 hours. What is the MOST cost-effective S3 storage class?', 'multiple-choice', 'S3 Standard', 'Too expensive for long-term archival.', 'S3 Glacier Flexible Retrieval', 'More expensive than Deep Archive with faster retrieval not needed.', 'S3 Intelligent-Tiering', 'Best for unpredictable access patterns not long-term archive.', 'S3 Glacier Deep Archive', 'Lowest-cost storage class designed for long-term retention.', None, None, None, None, '4', 'S3 Glacier Deep Archive is the cheapest option for long-term data archival where a retrieval time of 12-48 hours is acceptable.', 'Design Cost-Optimized Architectures'],
    ['A critical application on EC2 instances must be highly available and withstand the failure of a single Availability Zone. What is the BEST design?', 'multiple-choice', 'Deploy instances in one AZ with multiple instance types', 'This does not protect against an AZ failure.', 'Deploy instances across multiple Availability Zones', 'This ensures high availability as traffic can be routed to healthy AZs.', 'Deploy a standby set in another AWS Region', 'This is a DR strategy and is more complex than required.', 'Use Spot Instances to automatically replace failed ones', 'Spot Instances can be interrupted and are not for critical stateful apps.', None, None, None, None, '2', 'Deploying EC2 instances across multiple AZs with an Application Load Balancer allows for automatic failover if one AZ becomes unavailable.', 'Design Resilient Architectures'],
    ['A developer requires temporary credentials to access an S3 bucket expiring after 1 hour. Which service should be used?', 'multiple-choice', 'IAM Roles', 'IAM Roles define permissions but do not issue temporary credentials directly.', 'AWS Security Token Service (STS)', 'STS is designed to grant temporary limited-privilege credentials.', 'AWS Secrets Manager', 'This service stores and rotates secrets like passwords but does not grant temporary access.', 'Amazon Cognito', 'Cognito is for application user identity not for AWS resource credentials for developers.', None, None, None, None, '2', 'AWS STS (Security Token Service) AssumeRole API call is used to obtain temporary security credentials with defined permissions and a set expiration time.', 'Design Secure Architectures'],
    ['An application requires a shared file system that can be mounted on multiple EC2 instances simultaneously using the NFS protocol. Which storage solution should be used?', 'multiple-choice', 'Amazon EBS Multi-Attach', 'This is block storage not a shared file system and is limited to one AZ.', 'Amazon S3', 'S3 is an object store and does not support the NFS protocol for EC2 mounting.', 'Amazon EFS', 'EFS is a fully managed scalable NFS-compliant file system.', 'Amazon EC2 Instance Store', 'Instance store is ephemeral block storage tied to a single EC2 instance.', None, None, None, None, '3', 'Amazon EFS is a managed NFS file system that can be mounted on thousands of EC2 instances concurrently providing a shared storage solution.', 'Design High-Performing Architectures'],
    ['How can a company ensure that all new objects uploaded to any S3 bucket in their AWS account are encrypted by default?', 'multiple-choice', 'Use an SCP to deny unencrypted uploads', 'This can be complex to manage and less direct.', 'Manually enable encryption on each new bucket', 'This is not an automated or enforceable policy.', 'Enable S3 Default Encryption in the account settings', 'This is the simplest method to enforce encryption for all new objects account-wide.', 'Run a daily script to encrypt objects', 'This is a reactive approach and does not prevent unencrypted objects from being created.', None, None, None, None, '3', 'Enabling S3 Default Encryption at the account level is a straightforward way to ensure all new objects are encrypted at rest using SSE-S3 or SSE-KMS.', 'Design Secure Architectures'],
    ['A web application behind an Application Load Balancer needs protection from common web exploits like SQL injection and XSS. Which AWS service is most suitable?', 'multiple-choice', 'AWS Shield', 'Shield provides DDoS protection not protection from application-layer attacks.', 'AWS WAF', 'WAF is a web application firewall that filters traffic based on rules to block attacks like SQL injection.', 'Amazon GuardDuty', 'GuardDuty is a threat detection service that analyzes logs not a real-time firewall.', 'AWS Firewall Manager', 'This service manages firewall rules across accounts but is not the firewall itself.', None, None, None, None, '2', 'AWS WAF integrates with Application Load Balancers to inspect web requests and block malicious traffic based on defined security rules.', 'Design Secure Architectures'],
    ['A company needs a dedicated private and low-latency network connection between its on-premises data center and AWS. Which service should be used?', 'multiple-choice', 'AWS Site-to-Site VPN', 'A VPN connection uses the public internet and does not offer consistent low latency.', 'AWS Direct Connect', 'Direct Connect provides a dedicated private connection for consistent performance.', 'VPC Peering', 'This connects VPCs to each other not to an on-premises location.', 'AWS Transit Gateway', 'This is a network hub and still requires a VPN or Direct Connect for the on-premises link.', None, None, None, None, '2', 'AWS Direct Connect establishes a private dedicated physical network connection bypassing the public internet for consistent low-latency performance.', 'Design High-Performing Architectures'],
    ['An application in a private subnet needs to access a DynamoDB table without traversing the public internet. What is the most secure method?', 'multiple-choice', 'Use a NAT Gateway', 'A NAT Gateway routes traffic over the public internet.', 'Create a VPC Gateway Endpoint for DynamoDB', 'This creates a private connection within the AWS network.', 'Assign Public IPs to the instances', 'This exposes instances to the internet and is not secure.', 'Use an Internet Gateway', 'This provides a route to the public internet.', None, None, None, None, '2', 'A VPC Gateway Endpoint for DynamoDB routes traffic between your VPC and DynamoDB over the private AWS network enhancing security.', 'Design Secure Architectures'],
    ['A company has a disaster recovery requirement with an RTO of 15 minutes and an RPO of 1 hour. Which strategy is the most appropriate?', 'multiple-choice', 'Backup and Restore', 'This strategy has a high RTO typically hours and cannot meet a 15-minute target.', 'Pilot Light', 'Involves a minimal running environment faster than Backup and Restore but may not meet a 15-minute RTO.', 'Warm Standby', 'A scaled-down but fully functional version of the application runs in the DR region allowing for a fast scale-up.', 'Multi-Site Active-Active', 'Provides near-zero RTO but is the most complex and expensive strategy.', None, None, None, None, '3', 'The Warm Standby strategy balances cost and recovery time allowing a quick scale-up in the disaster recovery region to meet a 15-minute RTO.', 'Design Resilient Architectures'],
    ['An EC2 fleet processes messages from an SQS queue. The number of instances should scale based on the number of messages in the queue. What is the most efficient scaling method?', 'multiple-choice', 'Scale based on CPU utilization', 'CPU usage may not directly correlate with the queue length.', 'Scale based on the SQS ApproximateNumberOfMessagesVisible metric', 'This directly ties scaling to the workload ensuring efficient resource use.', 'Scale manually', 'This is not automated and is inefficient.', 'Use a scheduled scaling policy', 'This is for predictable traffic patterns not variable queue lengths.', None, None, None, None, '2', 'Using a target tracking scaling policy based on the ApproximateNumberOfMessagesVisible SQS metric allows the Auto Scaling group to adjust the instance count based on the actual workload.', 'Design High-Performing Architectures'],
    ['A company wants to run large-scale data processing jobs using frameworks like Apache Spark and Hadoop. Which managed service simplifies this process?', 'multiple-choice', 'Amazon RDS', 'RDS is a relational database service not for big data processing.', 'Amazon EMR', 'EMR is a managed service for running big data frameworks like Spark and Hadoop.', 'Amazon Redshift', 'Redshift is a data warehouse not a general-purpose processing framework.', 'AWS Lambda', 'Lambda is for short-running event-driven functions not for long-running distributed jobs.', None, None, None, None, '2', 'Amazon EMR (Elastic MapReduce) automates the setup scaling and management of clusters for big data frameworks simplifying large-scale data processing.', 'Design High-Performing Architectures'],
    ['A web application needs to store user session data with sub-millisecond latency. Which AWS service is the best fit?', 'multiple-choice', 'Amazon RDS', 'RDS is a disk-based database with higher latency.', 'Amazon DynamoDB', 'DynamoDB offers low single-digit millisecond latency but in-memory stores are faster.', 'Amazon ElastiCache for Redis', 'ElastiCache for Redis is an in-memory data store providing sub-millisecond latency ideal for session storage.', 'Amazon S3', 'S3 is an object store and is not suitable for low-latency session data.', None, None, None, None, '3', 'Amazon ElastiCache for Redis provides an in-memory key-value store with extremely low latency making it a popular choice for caching and session management.', 'Design High-Performing Architectures'],
    ['In a microservices architecture services need to communicate asynchronously. Which managed service acts as a reliable message broker?', 'multiple-choice', 'Amazon SNS', 'SNS is a publish/subscribe service for fan-out messaging not typically a message broker.', 'Amazon SQS', 'SQS is a fully managed message queuing service for decoupling microservices.', 'Amazon Kinesis Data Streams', 'Kinesis is for real-time data streaming not general-purpose messaging.', 'AWS Step Functions', 'Step Functions is a workflow orchestrator not a message broker.', None, None, None, None, '2', 'Amazon SQS (Simple Queue Service) provides a reliable and scalable message queue for decoupling components of a distributed system.', 'Design Resilient Architectures'],
    ['A company wants to provision its AWS infrastructure using code. Which service allows defining and deploying infrastructure from a template?', 'multiple-choice', 'AWS Elastic Beanstalk', 'Beanstalk is a PaaS that abstracts the underlying infrastructure.', 'AWS CloudFormation', 'CloudFormation allows you to model your infrastructure as code in templates.', 'AWS OpsWorks', 'OpsWorks is a configuration management service using Chef and Puppet.', 'AWS Config', 'Config is for auditing and compliance not for provisioning.', None, None, None, None, '2', 'AWS CloudFormation enables you to define your entire AWS infrastructure in a JSON or YAML template allowing for automated and repeatable deployments.', 'Design High-Performing Architectures'],
    ['A website with a global user base serves large static files. How can the company reduce latency and server load?', 'multiple-choice', 'AWS Global Accelerator', 'Global Accelerator is for dynamic content and applications not for caching static files.', 'Amazon CloudFront', 'CloudFront is a CDN that caches static content at edge locations close to users.', 'Elastic Load Balancing', 'ELB distributes traffic but does not cache content.', 'S3 Transfer Acceleration', 'This service speeds up uploads to S3 but does not serve content from edge locations.', None, None, None, None, '2', 'Amazon CloudFront caches static assets at edge locations worldwide reducing latency for users and offloading requests from the origin server.', 'Design High-Performing Architectures'],
    ['A company wants to run BI queries on its production RDS for PostgreSQL database without impacting performance. What is the best approach?', 'multiple-choice', 'Run queries during off-peak hours', 'This can still impact performance and may not be feasible for a 24/7 business.', 'Create a read replica of the database', 'A read replica allows you to offload read traffic from the primary instance.', 'Export data to S3 and query with Athena', 'This adds complexity and latency to the analytics process.', 'Migrate the database to Amazon Redshift', 'This is a complex data warehousing solution whereas a read replica is a simpler solution.', None, None, None, None, '2', 'Creating a read replica for an RDS database is the standard method for isolating read-heavy workloads like BI queries from the production database.', 'Design Resilient Architectures'],
    ['An application generates logs that are frequently accessed for the first 30 days then infrequently for a year. Which S3 storage class is most cost-effective?', 'multiple-choice', 'S3 Standard', 'This is expensive for long-term storage of infrequently accessed data.', 'S3 Glacier Flexible Retrieval', 'This is for archival data and has a retrieval time of minutes to hours.', 'S3 Intelligent-Tiering', 'This automatically moves data between access tiers based on usage patterns optimizing cost.', 'S3 Standard-Infrequent Access', 'This has a retrieval fee and is best for data that is known to be infrequently accessed.', None, None, None, None, '3', 'S3 Intelligent-Tiering automatically optimizes storage costs by moving data to the most cost-effective tier without performance impact or operational overhead.', 'Design Cost-Optimized Architectures'],
    ['A serverless application built with AWS Lambda needs a fast scalable and fully managed NoSQL database. Which AWS service is the best choice?', 'multiple-choice', 'Amazon RDS', 'RDS is a relational database service not NoSQL.', 'Amazon DynamoDB', 'DynamoDB is a serverless NoSQL database with single-digit millisecond latency.', 'Amazon Redshift', 'Redshift is a data warehouse not a transactional database.', 'Amazon ElastiCache', 'ElastiCache is an in-memory cache not a persistent database.', None, None, None, None, '2', 'Amazon DynamoDB is a fully managed serverless NoSQL database that integrates seamlessly with AWS Lambda providing high performance at any scale.', 'Design High-Performing Architectures'],
    ['Which service should be used to record all API calls made within an AWS account for security and auditing purposes?', 'multiple-choice', 'Amazon CloudWatch', 'CloudWatch monitors performance metrics and logs but does not record all API calls.', 'AWS CloudTrail', 'CloudTrail logs all API activity across your AWS account.', 'Amazon S3 Access Logs', 'These logs are specific to S3 buckets not the entire account.', 'VPC Flow Logs', 'Flow Logs capture network traffic information not API calls.', None, None, None, None, '2', 'AWS CloudTrail is a service that provides event history of your AWS account activity including actions taken through the AWS Management Console AWS SDKs and command line tools.', 'Design Secure Architectures'],
    ['A developer wants to run a containerized application without managing the underlying EC2 instances paying only for consumed resources. Which service and launch type should be used?', 'multiple-choice', 'Amazon ECS with EC2 launch type', 'This requires you to manage the EC2 instances in the cluster.', 'Amazon ECS with Fargate launch type', 'Fargate is a serverless compute engine for containers where you pay for vCPU and memory.', 'Amazon EKS with EC2 launch type', 'This also requires you to manage the worker nodes.', 'AWS Elastic Beanstalk with Docker', 'Beanstalk abstracts but still provisions and charges for the underlying EC2 instances.', None, None, None, None, '2', 'Amazon ECS with the Fargate launch type allows you to run containers without managing servers and you are billed for the resources your application consumes.', 'Design Cost-Optimized Architectures'],
    ['A company needs a secure and cost-effective connection from its on-premises data center to its VPC for moderate data transfer. Which service is most appropriate?', 'multiple-choice', 'AWS Direct Connect', 'Direct Connect is a dedicated connection which is more expensive and for high-bandwidth needs.', 'AWS Site-to-Site VPN', 'A VPN provides a secure encrypted connection over the internet and is cost-effective.', 'VPC Peering', 'VPC Peering connects two VPCs not an on-premises network.', 'AWS Transit Gateway', 'Transit Gateway is a network hub and still requires a VPN or Direct Connect connection.', None, None, None, None, '2', 'An AWS Site-to-Site VPN is a secure and cost-effective solution for connecting an on-premises network to a VPC over the internet.', 'Design Secure Architectures'],
    ['How can a company protect data in an S3 bucket from being accidentally deleted or overwritten?', 'multiple-choice', 'Enable S3 Versioning', 'Versioning keeps multiple versions of an object allowing for recovery.', 'Enable Cross-Region Replication', 'This is for disaster recovery not for protecting against accidental deletions.', 'Use S3 Lifecycle policies', 'Lifecycle policies manage object transitions and expiration not protection from deletion.', 'Enable MFA Delete', 'MFA Delete adds a layer of security but does not allow for recovery like versioning does.', None, None, None, None, '1', 'S3 Versioning is the primary mechanism for protecting against accidental deletion as it allows you to restore previous versions of an object.', 'Design Resilient Architectures'],
    ['An application requires a POSIX-compliant file system that can be shared across multiple EC2 instances. Which AWS service should be used?', 'multiple-choice', 'Amazon S3', 'S3 is an object store not a POSIX-compliant file system.', 'Amazon EFS', 'EFS provides a fully managed scalable POSIX-compliant file system.', 'Amazon EBS', 'EBS provides block storage for a single EC2 instance.', 'AWS Storage Gateway', 'Storage Gateway is a hybrid storage service not a shared file system for EC2 instances.', None, None, None, None, '2', 'Amazon EFS is a managed file storage service that provides a POSIX-compliant file system that can be mounted on multiple EC2 instances.', 'Design High-Performing Architectures'],
    ['An application needs to securely store and automatically rotate database passwords. Which service is best suited for this task?', 'multiple-choice', 'AWS Key Management Service (KMS)', 'KMS manages encryption keys but does not handle secret rotation.', 'AWS Secrets Manager', 'Secrets Manager stores secrets and can automatically rotate credentials for services like RDS.', 'AWS Systems Manager Parameter Store', 'Parameter Store can store secrets but does not have built-in automatic rotation for database passwords.', 'AWS Certificate Manager (ACM)', 'ACM is for managing SSL/TLS certificates.', None, None, None, None, '2', 'AWS Secrets Manager is designed for storing and rotating secrets with native integration for rotating database credentials on Amazon RDS.', 'Design Secure Architectures'],
    ['What is the most cost-effective and scalable way to host a static website on AWS?', 'multiple-choice', 'Amazon EC2 with an Elastic IP', 'This is more expensive and less scalable than a serverless approach.', 'Amazon S3 with Amazon CloudFront', 'Hosting on S3 is low-cost and CloudFront provides scalable and low-latency content delivery.', 'AWS Elastic Beanstalk', 'Beanstalk is for dynamic applications and is not the most cost-effective for static sites.', 'Amazon Lightsail', 'Lightsail is a simplified VPS but S3 with CloudFront is generally more scalable and cost-effective.', None, None, None, None, '2', 'Hosting a static website on Amazon S3 and distributing it with Amazon CloudFront is a highly scalable available and cost-effective solution.', 'Design Cost-Optimized Architectures'],
    ['A legacy application requires access to a file share in the cloud using the SMB protocol. Which AWS service should be used?', 'multiple-choice', 'Amazon EFS', 'EFS provides NFS file shares not SMB.', 'Amazon S3', 'S3 is an object store not a file share.', 'Amazon FSx for Windows File Server', 'FSx for Windows File Server provides a fully managed native Windows file system with SMB support.', 'AWS Storage Gateway in File Gateway mode', 'File Gateway provides a file interface to S3 but FSx is a more native solution.', None, None, None, None, '3', 'Amazon FSx for Windows File Server is the best choice for applications requiring a managed SMB file share in the cloud.', 'Design High-Performing Architectures'],
    ['How can a company prevent developers from launching specific large EC2 instance types across its entire AWS organization?', 'multiple-choice', 'Use an IAM policy', 'IAM policies must be applied to each user or role which is hard to manage.', 'Use an AWS Organizations Service Control Policy (SCP)', 'SCPs can set permission guardrails for all accounts in an organization.', 'Use AWS Config to terminate non-compliant instances', 'This is a reactive approach not a preventive one.', 'Use AWS Trusted Advisor', 'Trusted Advisor provides recommendations but does not enforce policies.', None, None, None, None, '2', 'A Service Control Policy (SCP) in AWS Organizations is the most effective way to enforce restrictions such as disallowing certain instance types across an entire organization.', 'Design Secure Architectures'],
    ['A company needs to process real-time streaming data from thousands of IoT devices in order. Which AWS service is most appropriate?', 'multiple-choice', 'Amazon SQS', 'SQS is a message queue not a real-time streaming service.', 'Amazon Kinesis Data Streams', 'Kinesis is designed for real-time processing of streaming data at scale with ordered records.', 'Amazon SNS', 'SNS is a pub/sub messaging service and does not guarantee order.', 'AWS Glue', 'Glue is an ETL service for batch processing not real-time streams.', None, None, None, None, '2', 'Amazon Kinesis Data Streams is built for ingesting and processing large-scale real-time data streams with guaranteed ordering of records within a shard.', 'Design High-Performing Architectures'],
    ['A company wants to encrypt objects in an S3 bucket and manage its own encryption keys. Which S3 encryption option should be used?', 'multiple-choice', 'Server-Side Encryption with S3-Managed Keys (SSE-S3)', 'With SSE-S3 AWS manages the encryption keys.', 'Server-Side Encryption with KMS-Managed Keys (SSE-KMS)', 'With SSE-KMS you can manage the keys in KMS but AWS still controls the key material.', 'Server-Side Encryption with Customer-Provided Keys (SSE-C)', 'With SSE-C you provide your own encryption key with each request.', 'Client-Side Encryption', 'With client-side encryption you encrypt the data before uploading it to S3.', None, None, None, None, '3', 'Server-Side Encryption with Customer-Provided Keys (SSE-C) allows you to manage your own encryption keys while having S3 perform the encryption and decryption.', 'Design Secure Architectures'],
    ['How can a company improve the read performance of its Amazon RDS for MySQL database?', 'multiple-choice', 'Enable Multi-AZ', 'Multi-AZ provides high availability not read scaling.', 'Create a read replica', 'Read replicas offload read traffic from the primary database instance.', 'Increase the instance size', 'This can improve performance but is not the most cost-effective solution for read-heavy workloads.', 'Use Amazon ElastiCache', 'Caching can improve performance but a read replica is a more direct solution for offloading read queries.', None, None, None, None, '2', 'Creating one or more read replicas for an RDS database is the standard method for scaling read-intensive workloads.', 'Design High-Performing Architectures'],
    ['A company has a stateless application that can tolerate interruptions. Which EC2 purchasing option is the most cost-effective?', 'multiple-choice', 'On-Demand Instances', 'On-Demand instances are flexible but are not the cheapest option.', 'Reserved Instances', 'Reserved Instances offer a discount but Spot Instances are more cost-effective for interruptible workloads.', 'Spot Instances', 'Spot Instances offer the highest discount for workloads that can be interrupted.', 'Dedicated Hosts', 'Dedicated Hosts are the most expensive option and are used for compliance and licensing.', None, None, None, None, '3', 'Spot Instances allow you to take advantage of unused EC2 capacity at significant discounts making them ideal for stateless and fault-tolerant applications.', 'Design Cost-Optimized Architectures'],
    ['Which service should a company use to centrally manage and govern its multiple AWS accounts?', 'multiple-choice', 'AWS Systems Manager', 'Systems Manager is for managing instances and resources within an account.', 'AWS Organizations', 'AWS Organizations allows you to centrally manage and govern your environment as you grow and scale your AWS resources.', 'AWS Config', 'AWS Config is for auditing resource configurations not managing multiple accounts.', 'AWS Control Tower', 'Control Tower uses Organizations to set up a landing zone but Organizations is the core management service.', None, None, None, None, '2', 'AWS Organizations helps you centrally manage billing control access and share resources across multiple AWS accounts.', 'Design Secure Architectures'],
    ['An application needs to store large objects that are accessed once or twice a month and requires retrieval within minutes. Which S3 storage class is best?', 'multiple-choice', 'S3 Standard-Infrequent Access', 'S3 Standard-IA offers millisecond retrieval and is more expensive than Glacier Instant Retrieval.', 'S3 Glacier Instant Retrieval', 'This class provides low-cost storage for long-lived data that is rarely accessed but requires millisecond retrieval.', 'S3 Glacier Flexible Retrieval', 'This has a retrieval time of minutes to hours.', 'S3 Glacier Deep Archive', 'This has a retrieval time of 12-48 hours.', None, None, None, None, '2', 'S3 Glacier Instant Retrieval is the most cost-effective for data that is accessed rarely but needs to be available in milliseconds when requested.', 'Design Cost-Optimized Architectures'],
    ['What is the best way to handle a sudden surge in traffic for a web application to maintain performance?', 'multiple-choice', 'Manually add more EC2 instances', 'Manual intervention is slow and prone to error.', 'Use an Auto Scaling group with a target tracking policy', 'Auto Scaling automatically adjusts capacity based on metrics like CPU or request count.', 'Increase the size of existing EC2 instances', 'Vertical scaling (scaling up) requires downtime and is less flexible than horizontal scaling.', 'Use a bigger Load Balancer', 'The load balancer handles traffic distribution but the backend instances need to scale to handle the load.', None, None, None, None, '2', 'An Auto Scaling group with a target tracking policy ensures that the application has the right number of instances to handle the current load maintaining performance.', 'Design High-Performing Architectures'],
    ['A company needs to store data in a way that it can be accessed by multiple EC2 instances in different Availability Zones simultaneously. Which service is suitable?', 'multiple-choice', 'Amazon EBS', 'EBS volumes are AZ-specific and can generally only be attached to one instance.', 'Amazon S3', 'S3 is an object store not a file system for simultaneous instance mounting.', 'Amazon EFS', 'EFS is a shared file system that can be accessed by instances across multiple AZs within a region.', 'Amazon FSx for Lustre', 'FSx for Lustre is for high-performance computing not general shared storage across AZs.', None, None, None, None, '3', 'Amazon EFS is designed to provide shared file storage that is highly available and durable across multiple Availability Zones.', 'Design Resilient Architectures'],
    ['How can a company ensure that their database is highly available and can automatically fail over to another Availability Zone?', 'multiple-choice', 'Enable Read Replicas', 'Read replicas are for scaling reads not for automatic high availability failover.', 'Use Amazon RDS in a Multi-AZ deployment', 'Multi-AZ deployments provide high availability and automatic failover support.', 'Perform regular manual backups', 'Backups are for data recovery not for providing high availability or automatic failover.', 'Use Amazon Aurora with Global Database', 'Global Database is for cross-region disaster recovery not for single-region high availability.', None, None, None, None, '2', 'Amazon RDS Multi-AZ deployments automatically provision and maintain a synchronous standby replica in a different Availability Zone for high availability.', 'Design Resilient Architectures'],
    ['Which AWS service provides a simple way to create and manage a collection of related AWS resources in a repeatable manner?', 'multiple-choice', 'AWS Systems Manager', 'Systems Manager is for operational tasks and resource management not provisioning.', 'AWS CloudFormation', 'CloudFormation allows you to use programming languages or a simple text file to model and provision all the resources needed for your applications.', 'AWS Elastic Beanstalk', 'Beanstalk is a service for deploying and scaling web applications not for managing general collections of resources.', 'AWS OpsWorks', 'OpsWorks is a configuration management service not a general resource provisioning tool.', None, None, None, None, '2', 'AWS CloudFormation provides a common language for you to describe and provision all the infrastructure resources in your cloud environment.', 'Design High-Performing Architectures'],
    ['A company wants to host a highly available database with a millisecond-level latency for a globally distributed application. Which service should they use?', 'multiple-choice', 'Amazon RDS with Read Replicas', 'RDS read replicas have higher latency for global distribution.', 'Amazon DynamoDB with Global Tables', 'Global Tables provide a fully managed multi-region multi-active database with low latency.', 'Amazon Aurora with Read Replicas', 'Aurora read replicas are efficient but Global Tables is more suited for multi-active global needs.', 'Amazon Redshift', 'Redshift is a data warehouse not a transactional database for low-latency applications.', None, None, None, None, '2', 'Amazon DynamoDB Global Tables provide a multi-region multi-active database solution that delivers fast local read and write performance.', 'Design Resilient Architectures'],
    ['How can a company monitor the health of its application and automatically route traffic away from unhealthy instances?', 'multiple-choice', 'Use Amazon CloudWatch Alarms', 'Alarms can notify you of issues but do not route traffic themselves.', 'Use an Elastic Load Balancer with health checks', 'ELB health checks monitor the status of targets and route traffic only to healthy ones.', 'Use AWS Config', 'AWS Config is for resource auditing and compliance not for real-time traffic routing.', 'Use Amazon Route 53 with health checks', 'Route 53 health checks can be used for DNS failover but ELB is more direct for application instances.', None, None, None, None, '2', 'Elastic Load Balancing automatically performs health checks on its registered targets and ensures that only healthy targets receive traffic.', 'Design Resilient Architectures'],
    ['An application needs to process a large number of images and requires high-performance block storage. Which service is best?', 'multiple-choice', 'Amazon S3', 'S3 is an object store and is not suitable for high-performance block storage.', 'Amazon EBS', 'EBS provides high-performance block storage volumes for use with EC2 instances.', 'Amazon EFS', 'EFS is a shared file system which may not provide the same block-level performance for image processing.', 'Amazon EC2 Instance Store', 'Instance store is ephemeral and should not be used for persistent image data.', None, None, None, None, '2', 'Amazon EBS provides a variety of volume types that can be tailored to the performance and capacity requirements of your workload.', 'Design High-Performing Architectures'],
    ['A company wants to decouple its application components to improve scalability and reliability. Which service should they use?', 'multiple-choice', 'Amazon EC2', 'EC2 is for compute and does not natively decouple components.', 'Amazon SQS', 'SQS is a message queuing service that allows you to decouple and scale microservices and distributed systems.', 'Amazon RDS', 'RDS is a relational database service and is not used for decoupling components.', 'AWS Step Functions', 'Step Functions is for workflow orchestration which can help but SQS is the primary service for decoupling.', None, None, None, None, '2', 'Amazon SQS enables you to decouple and scale microservices distributed systems and serverless applications.', 'Design Resilient Architectures'],
    ['Which AWS service helps you migrate databases to AWS quickly and securely with minimal downtime?', 'multiple-choice', 'AWS Snowball', 'Snowball is for large-scale data transfer not specifically for database migration.', 'AWS Database Migration Service (DMS)', 'DMS helps you migrate databases to AWS quickly and securely while the source database remains operational.', 'AWS Application Discovery Service', 'This service helps you plan your migration by discovering your on-premises applications.', 'AWS DataSync', 'DataSync is for moving large amounts of data between on-premises storage and AWS not for live database migrations.', None, None, None, None, '2', 'AWS DMS supports both homogenous migrations (e.g. Oracle to Oracle) and heterogeneous migrations (e.g. Oracle to Aurora).', 'Design High-Performing Architectures'],
    ['How can a company control which IP addresses are allowed to access their web servers running on EC2 instances?', 'multiple-choice', 'Use IAM Policies', 'IAM policies control access to AWS resources and APIs not network traffic to EC2 instances.', 'Use Security Groups', 'Security groups act as a virtual firewall for your EC2 instances to control inbound and outbound traffic.', 'Use Network ACLs', 'NACLs control traffic at the subnet level but security groups are the first line of defense at the instance level.', 'Use AWS WAF', 'WAF protects against web exploits but security groups are the primary way to filter by IP address.', None, None, None, None, '2', 'Security groups allow you to define rules based on IP addresses and protocols to secure your EC2 instances.', 'Design Secure Architectures'],
    ['A company needs to store sensitive data in S3 and must ensure that the data is encrypted before it is sent to AWS. Which method should they use?', 'multiple-choice', 'SSE-S3', 'SSE-S3 is server-side encryption managed by AWS.', 'SSE-KMS', 'SSE-KMS is server-side encryption with keys managed in KMS.', 'Client-Side Encryption', 'Client-side encryption involves encrypting data on the client side before it is uploaded to S3.', 'SSE-C', 'SSE-C is server-side encryption with customer-provided keys.', None, None, None, None, '3', 'With client-side encryption you manage the encryption process the keys and the related tools for encrypting data before it is sent to AWS.', 'Design Secure Architectures'],
    ['What is the best way to handle long-running and complex workflows in a serverless application?', 'multiple-choice', 'Use multiple AWS Lambda functions', 'Chaining Lambda functions can be complex to manage and monitor.', 'Use AWS Step Functions', 'Step Functions is a serverless orchestrator that makes it easy to coordinate multiple AWS services into serverless workflows.', 'Use Amazon SQS', 'SQS is for messaging not for orchestrating complex workflows.', 'Use Amazon SNS', 'SNS is for pub/sub messaging and does not handle workflow orchestration.', None, None, None, None, '2', 'AWS Step Functions provides a graphical console to visualize and coordinate the steps of your application as a series of event-driven steps.', 'Design High-Performing Architectures'],
    ['A company wants to run a containerized application on a managed Kubernetes service. Which AWS service should they use?', 'multiple-choice', 'Amazon ECS', 'ECS is a managed container orchestration service but it is not Kubernetes.', 'Amazon EKS', 'Amazon EKS is a managed service that makes it easy for you to run Kubernetes on AWS.', 'AWS Fargate', 'Fargate is a compute engine for containers that can be used with both ECS and EKS.', 'AWS App Runner', 'App Runner is for deploying web applications directly from source code or container images not for managing Kubernetes.', None, None, None, None, '2', 'Amazon EKS is a certified Kubernetes-conformant service that simplifies the process of building and running Kubernetes clusters.', 'Design High-Performing Architectures'],
    ['Which service allows you to run code without provisioning or managing servers and you pay only for the compute time you consume?', 'multiple-choice', 'Amazon EC2', 'EC2 requires you to provision and manage servers.', 'AWS Lambda', 'Lambda is a serverless compute service that runs your code in response to events and automatically manages the underlying compute resources.', 'AWS Fargate', 'Fargate is a serverless compute engine for containers but you still define resource limits.', 'Amazon Lightsail', 'Lightsail is a simplified VPS service that still requires server management.', None, None, None, None, '2', 'AWS Lambda is a key component of serverless architectures allowing you to run code without the overhead of managing servers.', 'Design High-Performing Architectures'],
    ['A company needs to store and analyze large amounts of data for business intelligence. Which AWS service is a managed data warehouse?', 'multiple-choice', 'Amazon RDS', 'RDS is for transactional databases not for large-scale data warehousing.', 'Amazon Redshift', 'Amazon Redshift is a fast fully managed data warehouse that makes it simple and cost-effective to analyze all your data.', 'Amazon Athena', 'Athena is an interactive query service for data in S3 not a data warehouse.', 'Amazon EMR', 'EMR is for big data processing using frameworks like Spark and Hadoop.', None, None, None, None, '2', 'Amazon Redshift uses SQL to analyze structured and semi-structured data across data warehouses operational databases and data lakes.', 'Design High-Performing Architectures'],
    ['How can a company protect their web application from distributed denial-of-service (DDoS) attacks?', 'multiple-choice', 'Use Security Groups', 'Security groups provide basic firewall protection but are not designed to stop DDoS attacks.', 'Use AWS Shield', 'AWS Shield is a managed Distributed Denial of Service (DDoS) protection service that safeguards applications running on AWS.', 'Use AWS WAF', 'WAF can help block some DDoS-related traffic but Shield is the primary service for DDoS protection.', 'Use Amazon Inspector', 'Inspector is a security assessment service not a DDoS protection service.', None, None, None, None, '2', 'AWS Shield provides always-on detection and automatic inline mitigations that minimize application downtime and latency.', 'Design Secure Architectures'],
    ['A company wants to store data that is rarely accessed but must be retrievable within milliseconds. Which S3 storage class should they use?', 'multiple-choice', 'S3 Standard-IA', 'Standard-IA is for infrequently accessed data with millisecond retrieval.', 'S3 Glacier Flexible Retrieval', 'Glacier has a retrieval time of minutes to hours.', 'S3 Glacier Deep Archive', 'Deep Archive has a retrieval time of 12-48 hours.', 'S3 One Zone-IA', 'One Zone-IA is similar to Standard-IA but stores data in a single AZ which may not meet durability requirements.', None, None, None, None, '1', 'S3 Standard-IA is ideal for data that is infrequently accessed but requires rapid access when needed.', 'Design Cost-Optimized Architectures'],
    ['Which AWS service provides highly available and scalable DNS web services?', 'multiple-choice', 'Amazon VPC', 'VPC is for networking not DNS.', 'Amazon Route 53', 'Amazon Route 53 is a highly available and scalable cloud Domain Name System (DNS) web service.', 'AWS Direct Connect', 'Direct Connect is for private network connections not DNS.', 'Amazon CloudFront', 'CloudFront is a CDN not a DNS service.', None, None, None, None, '2', 'Route 53 effectively connects user requests to infrastructure running in AWS such as EC2 instances ELB load balancers or S3 buckets.', 'Design Resilient Architectures'],
    ['How can a company automate the process of detecting and remediating security issues in their AWS account?', 'multiple-choice', 'Use AWS Trusted Advisor', 'Trusted Advisor provides recommendations but does not automate remediation.', 'Use AWS Config with remediation actions', 'AWS Config monitors your resources and can automatically trigger remediation actions for non-compliant resources.', 'Use Amazon GuardDuty', 'GuardDuty detects threats but requires additional services like Lambda for automated remediation.', 'Use AWS Security Hub', 'Security Hub provides a centralized view of security alerts but automation is typically handled by Config or Lambda.', None, None, None, None, '2', 'AWS Config allows you to define rules and associate them with remediation actions using AWS Systems Manager Automation documents.', 'Design Secure Architectures'],
    ['A company needs to store large amounts of unstructured data and requires a highly durable and scalable solution. Which service should they use?', 'multiple-choice', 'Amazon RDS', 'RDS is for structured relational data.', 'Amazon S3', 'Amazon S3 is an object storage service that offers industry-leading scalability data availability security and performance.', 'Amazon EBS', 'EBS is block storage for EC2 instances and is not as scalable or durable as S3 for unstructured data.', 'Amazon EFS', 'EFS is a shared file system not an object store for unstructured data.', None, None, None, None, '2', 'Amazon S3 is designed for 99.999999999% (11 9s) of durability and can store and protect any amount of data.', 'Design High-Performing Architectures'],
    ['Which AWS service is a serverless event bus that makes it easy to connect applications using data from your own applications and AWS services?', 'multiple-choice', 'Amazon SNS', 'SNS is a pub/sub messaging service.', 'Amazon EventBridge', 'Amazon EventBridge is a serverless event bus that makes it easy to build event-driven applications at scale.', 'Amazon SQS', 'SQS is a message queuing service.', 'AWS Step Functions', 'Step Functions is a workflow orchestrator.', None, None, None, None, '2', 'EventBridge delivers a stream of real-time data from event sources such as Zendesk or Shopify to targets like AWS Lambda.', 'Design High-Performing Architectures'],
    ['A company wants to improve the performance of its global application by routing user traffic over the AWS global network. Which service should they use?', 'multiple-choice', 'Amazon CloudFront', 'CloudFront is a CDN for content delivery.', 'AWS Global Accelerator', 'AWS Global Accelerator uses the AWS global network to improve the performance and availability of your applications.', 'Amazon Route 53', 'Route 53 is a DNS service and while it can route traffic Global Accelerator provides more direct network-level performance improvements.', 'AWS Direct Connect', 'Direct Connect is for connecting on-premises networks to AWS not for routing global user traffic.', None, None, None, None, '2', 'Global Accelerator provides static IP addresses that act as a fixed entry point to your application endpoints in multiple AWS Regions.', 'Design High-Performing Architectures'],
    ['A company needs to migrate 50TB of data to S3 with limited bandwidth and time is critical. Which service is most suitable?', 'multiple-choice', 'AWS Snowball Edge', 'This is a physical device for large-scale data transfer.', 'AWS Direct Connect', 'This is a dedicated network connection which can be costly and time-consuming to set up.', 'S3 Transfer Acceleration', 'This service accelerates uploads over the internet.', 'AWS DataSync', 'This is an online data transfer service.', 'AWS Snowmobile', 'Snowmobile is for exabyte-scale data transfer.', None, None, None, '1', 'AWS Snowball Edge is a physical appliance that allows you to transfer large amounts of data to AWS offline which is faster than using the internet for a 50TB transfer with limited bandwidth.', 'Design Cost-Optimized Architectures'],
    ['How can a company ensure that only specific IAM users can access a particular S3 bucket?', 'multiple-choice', 'Use an IAM policy', 'IAM policies define permissions for users and roles.', 'Use an S3 bucket policy', 'A bucket policy is a resource-based policy that allows you to grant access to a bucket and its objects to specific IAM users.', 'Use S3 Access Control Lists (ACLs)', 'ACLs are a legacy access control mechanism and are not recommended for new use cases.', 'Use both IAM and bucket policies', 'While both can be used a bucket policy is often more direct for resource-level access control.', None, None, None, None, '2', 'S3 bucket policies are written in JSON and provide centralized access control to your S3 buckets.', 'Design Secure Architectures'],
    ['What is the best way to monitor the performance of your EC2 instances and receive alerts when CPU utilization is high?', 'multiple-choice', 'Use AWS Trusted Advisor', 'Trusted Advisor provides recommendations not real-time monitoring and alerts.', 'Use Amazon CloudWatch', 'CloudWatch monitors your AWS resources and the applications you run on AWS in real time and can trigger alarms.', 'Use AWS Config', 'AWS Config is for resource auditing and compliance not performance monitoring.', 'Use Amazon Inspector', 'Inspector is a security assessment service not a performance monitoring service.', None, None, None, None, '2', 'You can create a CloudWatch alarm to watch a single metric and perform one or more actions based on the value of the metric relative to a threshold over time.', 'Design High-Performing Architectures'],
    ['A company needs to store data for a long time at a very low cost and retrieval time can be up to several hours. Which service should they use?', 'multiple-choice', 'S3 Standard-IA', 'Standard-IA has millisecond retrieval and is more expensive than Glacier.', 'S3 Glacier Flexible Retrieval', 'Glacier Flexible Retrieval is a low-cost storage class for data that is rarely accessed and can be retrieved in minutes to hours.', 'S3 Standard', 'S3 Standard is the most expensive class for long-term archival.', 'S3 Intelligent-Tiering', 'Intelligent-Tiering automatically moves data but Glacier is cheaper for known archival data.', None, None, None, None, '2', 'S3 Glacier Flexible Retrieval is a cost-effective choice for backup and archival data that does not require immediate access.', 'Design Cost-Optimized Architectures'],
    ['How can a company ensure that their application is resilient to the failure of an entire AWS Region?', 'multiple-choice', 'Use Multi-AZ deployments', 'Multi-AZ is for resilience within a single region not across regions.', 'Implement a multi-region architecture', 'A multi-region architecture involves deploying the application in two or more AWS Regions to ensure availability if one region fails.', 'Use Amazon Route 53 with health checks', 'Route 53 can help with failover but the application must be deployed in the second region first.', 'Enable S3 Cross-Region Replication', 'CRR replicates data but you still need to deploy the application in the other region.', None, None, None, None, '2', 'Deploying your application in multiple regions provides the highest level of resilience and disaster recovery capability.', 'Design Resilient Architectures'],
    ['A company wants to decouple its application and handle spikes in traffic by using a message queue. Which service provides a FIFO (First-In-First-Out) queue?', 'multiple-choice', 'Amazon SNS', 'SNS is a pub/sub messaging service.', 'Amazon SQS', 'Amazon SQS offers FIFO queues that guarantee that messages are processed in the exact order that they are sent.', 'Amazon EventBridge', 'EventBridge is an event bus.', 'Amazon Kinesis', 'Kinesis is for streaming data not for simple message queuing.', None, None, None, None, '2', 'Amazon SQS FIFO queues are designed for applications that require messages to be processed in a strict order.', 'Design High-Performing Architectures'],
    ['How can you prevent specific IAM users from accessing a production S3 bucket?', 'multiple-choice', 'Use an IAM user policy with a Deny statement', 'This can be overridden by other policies.', 'Use an S3 bucket policy with a Deny statement', 'A bucket policy can explicitly deny access to specific principals.', 'Use S3 Access Control Lists (ACLs)', 'ACLs are a legacy access control mechanism and are not recommended for new use cases.', 'Use a Service Control Policy (SCP)', 'SCPs are for organization-wide guardrails not for specific resource access.', None, None, None, None, '2', 'An S3 bucket policy with an explicit Deny statement for a specific IAM user is a direct and effective way to block access to a bucket.', 'Design Secure Architectures'],
    ['What is the most cost-effective storage option for data that is accessed once per year but needs to be retrieved immediately?', 'multiple-choice', 'S3 Standard-Infrequent Access', 'This is more expensive than One Zone-IA.', 'S3 Glacier Flexible Retrieval', 'This has a retrieval time of minutes to hours.', 'S3 Glacier Deep Archive', 'This has a retrieval time of 12-48 hours.', 'S3 One Zone-Infrequent Access', 'This is the cheapest option for infrequently accessed data that needs immediate retrieval.', None, None, None, None, '4', 'S3 One Zone-IA is 20% cheaper than S3 Standard-IA and is suitable for data that is infrequently accessed but requires millisecond retrieval.', 'Design Cost-Optimized Architectures']
]

# Normalize all rows
data_normalized = [normalize_row(row) for row in data]

# Create DataFrame
df = pd.DataFrame(data_normalized, columns=columns)

# Save CSV
df.to_csv('aws_developer_associate1.csv', index=False)
print("CSV successfully created: aws_developer_associate1.csv")