import pandas as pd

# Define columns
columns = [
    'Question', 'Question Type', 'Answer Option 1', 'Explanation 1', 
    'Answer Option 2', 'Explanation 2', 'Answer Option 3', 'Explanation 3', 
    'Answer Option 4', 'Explanation 4', 'Answer Option 5', 'Explanation 5', 
    'Answer Option 6', 'Explanation 6', 'Correct Answers', 'Overall Explanation', 'Domain'
]

# Helper to normalize each row to exactly 17 columns
def normalize_row(row):
    # Keep only the first 2 elements (Question, Type)
    base = row[:2]
    
    # Extract answers and explanations
    answers = row[2:-3]  # everything except Question, Type, Correct, Overall Explanation, Domain
    correct_answers = row[-3]
    overall_explanation = row[-2]
    domain = row[-1]
    
    # Pad answers/explanations to 6 pairs
    while len(answers) < 12:
        answers.append(None)
    
    # Trim answers if somehow longer than 12
    answers = answers[:12]
    
    # Combine everything
    return base + answers + [correct_answers, overall_explanation, domain]

# The 65 Questions Data
data = [
    # --- 20 Standard Multiple Choice Questions ---
    ['Which AWS service is best suited for automating the patching of managed instances on a schedule?', 'multiple-choice', 'AWS Systems Manager Patch Manager', 'Patch Manager automates the process of patching managed instances with security related updates.', 'Amazon Inspector', 'Inspector assesses applications for vulnerabilities but does not apply patches.', 'AWS Config', 'Config monitors compliance but does not apply patches.', 'AWS OpsWorks', 'OpsWorks is for configuration management but SSM is the native patching tool.', None, None, None, None, '1', 'AWS Systems Manager Patch Manager automates the process of patching managed instances with security related updates.', 'Configuration Management and IaC'],
    ['A company needs to implement a blue/green deployment strategy for an application running on EC2 instances behind an Application Load Balancer. Which AWS service facilitates this?', 'multiple-choice', 'AWS CodeDeploy', 'CodeDeploy supports blue/green deployments for EC2/On-Premises compute platforms.', 'AWS CodeBuild', 'CodeBuild is for compiling source code, not deployment.', 'AWS CodePipeline', 'CodePipeline orchestrates the release but CodeDeploy performs the actual deployment.', 'AWS CloudFormation', 'CloudFormation creates resources but CodeDeploy handles the traffic shifting logic best.', None, None, None, None, '1', 'AWS CodeDeploy provides a deployment method that shifts traffic from the original environment to the new environment.', 'SDLC Automation'],
    ['Which service should be used to centrally manage and audit configuration changes to AWS resources across multiple accounts?', 'multiple-choice', 'AWS Config', 'AWS Config provides a detailed view of the configuration of AWS resources in your AWS account.', 'AWS CloudTrail', 'CloudTrail logs API calls, not resource configuration states.', 'Amazon CloudWatch', 'CloudWatch is for monitoring metrics and logs.', 'AWS Systems Manager', 'SSM manages instances but Config is for auditing resource configuration.', None, None, None, None, '1', 'AWS Config enables you to assess, audit, and evaluate the configurations of your AWS resources.', 'Security and Compliance'],
    ['You need to encrypt environment variables for a Lambda function. Which service is integrated for this purpose?', 'multiple-choice', 'AWS Key Management Service (KMS)', 'Lambda uses KMS to encrypt environment variables at rest.', 'AWS Secrets Manager', 'Secrets Manager stores secrets but KMS is the underlying encryption mechanism for environment variables.', 'AWS Certificate Manager', 'ACM manages SSL/TLS certificates.', 'Amazon Macie', 'Macie discovers sensitive data in S3.', None, None, None, None, '1', 'When you create or update a Lambda function that uses environment variables, AWS Lambda encrypts them using the AWS Key Management Service.', 'Security and Compliance'],
    ['Which routing policy in Route 53 is best for testing a new version of a website with a small percentage of users?', 'multiple-choice', 'Weighted Routing', 'Weighted routing lets you associate multiple resources with a single domain name and choose how much traffic is routed to each.', 'Latency Routing', 'Latency routing is based on network latency.', 'Failover Routing', 'Failover is for DR.', 'Geolocation Routing', 'Geolocation is based on user location.', None, None, None, None, '1', 'Weighted routing enables you to split traffic between two versions of an application for A/B testing.', 'Resilient Cloud Solutions'],
    ['A DevOps engineer needs to capture and analyze logs from multiple AWS accounts in a central S3 bucket. What feature of CloudWatch Logs facilitates this?', 'multiple-choice', 'Subscription Filters', 'You can use subscription filters to deliver log events to Kinesis, Lambda, or Firehose (which can write to S3).', 'Metric Filters', 'Metric filters extract metric data from logs.', 'Log Groups', 'Log groups store logs.', 'Log Streams', 'Log streams are sequences of log events.', None, None, None, None, '1', 'Subscription filters allow you to stream log data to other services like Kinesis Firehose, which can deliver to S3.', 'Monitoring and Logging'],
    ['How can you ensure that an AWS CloudFormation stack update does not delete a database instance?', 'multiple-choice', 'Set the DeletionPolicy attribute to Retain', 'The DeletionPolicy attribute preserves resources when the stack is deleted.', 'Enable Stack Termination Protection', 'Termination protection prevents the whole stack from being deleted, but not individual resources during updates.', 'Use a Stack Policy', 'Stack policies prevent updates to specific resources during stack updates.', 'Use a Change Set', 'Change sets preview changes but do not prevent them.', None, None, None, None, '3', 'A stack policy is a JSON document that defines the update actions that can be performed on designated resources.', 'Configuration Management and IaC'],
    ['Which service provides a managed source control service that hosts private Git repositories?', 'multiple-choice', 'AWS CodeCommit', 'CodeCommit is a fully-managed source control service that hosts secure Git-based repositories.', 'AWS CodeStar', 'CodeStar is for project management.', 'AWS CodeBuild', 'CodeBuild is for building code.', 'AWS X-Ray', 'X-Ray is for debugging.', None, None, None, None, '1', 'AWS CodeCommit is a secure, highly scalable, managed source control service that hosts private Git repositories.', 'SDLC Automation'],
    ['A team needs to debug a distributed application based on microservices architecture. Which service helps visualize the service map and trace requests?', 'multiple-choice', 'AWS X-Ray', 'X-Ray helps developers analyze and debug production, distributed applications.', 'Amazon CloudWatch', 'CloudWatch monitors resources.', 'AWS CloudTrail', 'CloudTrail logs API activity.', 'AWS Config', 'Config audits resource configurations.', None, None, None, None, '1', 'AWS X-Ray provides an end-to-end view of requests as they travel through your application.', 'Monitoring and Logging'],
    ['Which deployment strategy allows you to deploy a new version of an application to a new environment and switch traffic instantly?', 'multiple-choice', 'Blue/Green Deployment', 'Blue/Green deployment creates a parallel environment and switches traffic.', 'Canary Deployment', 'Canary shifts traffic gradually.', 'Rolling Deployment', 'Rolling updates instances one by one.', 'In-place Deployment', 'In-place updates existing instances.', None, None, None, None, '1', 'Blue/green deployment is a technique that reduces downtime and risk by running two identical production environments.', 'SDLC Automation'],
    ['What feature of AWS Auto Scaling allows you to scale based on the number of messages in an SQS queue?', 'multiple-choice', 'Target Tracking Scaling Policy', 'Target tracking scaling policies increase or decrease the current capacity of the group based on a target value for a specific metric.', 'Scheduled Scaling', 'Scheduled scaling is based on time.', 'Predictive Scaling', 'Predictive scaling forecasts future load.', 'Manual Scaling', 'Manual scaling is not automatic.', None, None, None, None, '1', 'Target tracking scaling policies simplify scaling by managing the scaling adjustment for you.', 'Resilient Cloud Solutions'],
    ['You need to store Docker images for your organization. Which service should you use?', 'multiple-choice', 'Amazon Elastic Container Registry (ECR)', 'ECR is a fully-managed Docker container registry.', 'Amazon S3', 'S3 stores objects, not container images natively.', 'AWS CodeBuild', 'CodeBuild builds images but does not store them long-term.', 'AWS Lambda', 'Lambda runs code.', None, None, None, None, '1', 'Amazon ECR is a fully managed Docker container registry that makes it easy to store, manage, and deploy Docker container images.', 'SDLC Automation'],
    ['Which service can be used to notify an on-call engineer via SMS when a CloudWatch Alarm state changes?', 'multiple-choice', 'Amazon Simple Notification Service (SNS)', 'SNS is a fully managed messaging service for both application-to-application and application-to-person communication.', 'Amazon Simple Queue Service (SQS)', 'SQS is a message queue service.', 'AWS Lambda', 'Lambda runs code.', 'Amazon SES', 'SES is for email.', None, None, None, None, '1', 'You can configure CloudWatch alarms to send a message to an SNS topic when the alarm changes state.', 'Incident and Event Response'],
    ['How can you automate the creation of a multi-region architecture using Infrastructure as Code?', 'multiple-choice', 'Use CloudFormation StackSets', 'StackSets allow you to create, update, or delete stacks across multiple accounts and regions.', 'Use CloudFormation Nested Stacks', 'Nested stacks manage complexity but not necessarily multi-region deployment directly.', 'Use CodeDeploy', 'CodeDeploy deploys applications.', 'Use Auto Scaling Groups', 'ASGs manage instances.', None, None, None, None, '1', 'AWS CloudFormation StackSets extends the functionality of stacks by enabling you to create, update, or delete stacks across multiple accounts and regions.', 'Configuration Management and IaC'],
    ['Which service allows you to inspect packages for common vulnerabilities and exposures (CVEs)?', 'multiple-choice', 'Amazon Inspector', 'Amazon Inspector tests the network accessibility of your EC2 instances and the security state of your applications.', 'AWS Shield', 'Shield protects against DDoS.', 'AWS WAF', 'WAF protects web applications.', 'AWS GuardDuty', 'GuardDuty monitors for malicious activity.', None, None, None, None, '1', 'Amazon Inspector helps you improve the security and compliance of your applications.', 'Security and Compliance'],
    ['What is the most secure way to grant an EC2 instance access to an S3 bucket?', 'multiple-choice', 'Attach an IAM Role to the instance', 'IAM roles for EC2 instances provide temporary credentials.', 'Store access keys in a configuration file', 'Storing long-term credentials is a security risk.', 'Store access keys in the code', 'Hardcoding credentials is a security risk.', 'Make the S3 bucket public', 'Making the bucket public exposes data.', None, None, None, None, '1', 'IAM roles for EC2 allow applications running on the instance to use temporary security credentials.', 'Security and Compliance'],
    ['Which service provides a centralized view of security alerts and compliance status across AWS accounts?', 'multiple-choice', 'AWS Security Hub', 'Security Hub gives you a comprehensive view of your high-priority security alerts and compliance status.', 'Amazon GuardDuty', 'GuardDuty provides threat detection.', 'AWS CloudTrail', 'CloudTrail logs API calls.', 'AWS Config', 'Config records configurations.', None, None, None, None, '1', 'AWS Security Hub provides a comprehensive view of your security state within AWS.', 'Security and Compliance'],
    ['You want to run a script on all your EC2 instances to install a security patch. Which service is best?', 'multiple-choice', 'AWS Systems Manager Run Command', 'Run Command lets you remotely and securely manage the configuration of your managed instances.', 'SSH into each instance', 'Manual SSH is not scalable.', 'User Data', 'User Data only runs at launch.', 'AWS Lambda', 'Lambda runs serverless code, not directly on instances.', None, None, None, None, '1', 'AWS Systems Manager Run Command allows you to automate common administrative tasks and perform one-time configuration changes at scale.', 'Configuration Management and IaC'],
    ['Which database service enables you to create a global database that spans multiple AWS Regions?', 'multiple-choice', 'Amazon Aurora', 'Aurora Global Database is designed for globally distributed applications.', 'Amazon RDS for MariaDB', 'Standard RDS supports read replicas but Aurora Global Database provides lower latency.', 'Amazon DynamoDB', 'DynamoDB Global Tables is also an option, but Aurora is relational.', 'Amazon Redshift', 'Redshift is a data warehouse.', None, None, None, None, '1', 'Amazon Aurora Global Database allows a single Amazon Aurora database to span multiple AWS Regions.', 'Resilient Cloud Solutions'],
    ['How can you prevent accidental deletion of an S3 bucket?', 'multiple-choice', 'Enable MFA Delete', 'MFA Delete adds an extra layer of security.', 'Enable Versioning', 'Versioning protects objects, not the bucket itself.', 'Use Bucket Policies', 'Policies control access.', 'Use Encryption', 'Encryption protects data confidentiality.', None, None, None, None, '1', 'MFA Delete adds another layer of security by requiring multi-factor authentication for sensitive operations.', 'Security and Compliance'],

   # --- 10 True/False Questions (Corrected) ---
    ['AWS CloudFormation StackSets can deploy stacks across multiple AWS accounts and regions.', 'multiple-choice', 'True', None, 'False', None, None, None, None, None, None, None, None, None, '1', 'StackSets extend the capability of stacks by enabling you to create, update, or delete stacks across multiple accounts and regions with a single operation.', 'Configuration Management and IaC'],
    ['Amazon S3 buckets are global resources and their names must be unique across all AWS accounts.', 'multiple-choice', 'True', None, 'False', None, None, None, None, None, None, None, None, None, '1', 'S3 bucket names are globally unique across all AWS accounts.', 'Storage'],
    ['You can use AWS CodeDeploy to deploy applications to on-premises servers.', 'multiple-choice', 'True', None, 'False', None, None, None, None, None, None, None, None, None, '1', 'CodeDeploy automates code deployments to any instance, including EC2 instances and on-premises servers.', 'SDLC Automation'],
    ['Amazon DynamoDB is a relational database service.', 'multiple-choice', 'False', None, 'True', None, None, None, None, None, None, None, None, None, '2', 'DynamoDB is a key-value and document database (NoSQL), not relational.', 'Database'],
    ['Security Groups are stateful, meaning return traffic is automatically allowed.', 'multiple-choice', 'True', None, 'False', None, None, None, None, None, None, None, None, None, '1', 'Security groups are stateful; if you send a request from your instance, the response traffic for that request is allowed to flow in regardless of inbound security group rules.', 'Security and Compliance'],
    ['AWS Lambda functions can run for up to 1 hour.', 'multiple-choice', 'False', None, 'True', None, None, None, None, None, None, None, None, None, '2', 'The maximum execution duration per request for a Lambda function is 15 minutes.', 'Compute'],
    ['Amazon EBS volumes are automatically replicated across multiple Availability Zones.', 'multiple-choice', 'False', None, 'True', None, None, None, None, None, None, None, None, None, '2', 'EBS volumes are replicated within a specific Availability Zone, not across multiple AZs.', 'Storage'],
    ['AWS Trusted Advisor can check for potential cost savings.', 'multiple-choice', 'True', None, 'False', None, None, None, None, None, None, None, None, None, '1', 'Trusted Advisor provides recommendations in five categories: Cost Optimization, Security, Fault Tolerance, Performance, and Service Limits.', 'Cost Management'],
    ['AWS CloudTrail logs are stored indefinitely by default.', 'multiple-choice', 'False', None, 'True', None, None, None, None, None, None, None, None, None, '2', 'By default, CloudTrail keeps event history for 90 days. You must configure a trail to store logs longer.', 'Monitoring and Logging'],
    ['You can peer two VPCs in different AWS Regions.', 'multiple-choice', 'True', None, 'False', None, None, None, None, None, None, None, None, None, '1', 'VPC Peering connections can be established between VPCs in different regions (Inter-Region VPC Peering).', 'Networking'],

    # --- 15 Select Two Questions ---
    ['Which two actions help secure the root user of an AWS account? (Select two)', 'multi-select', 'Enable MFA', 'MFA adds a layer of protection.', 'Create access keys for the root user', 'Access keys should not be created for root.', 'Use the root user for daily tasks', 'Root should only be used for specific tasks.', 'Delete root user access keys', 'Removing keys prevents programmatic access.', 'Share the root password', 'Never share passwords.', None, None, '1,4', 'Enabling MFA and removing access keys are best practices for securing the root user.', 'Security and Compliance'],
    ['A company wants to decouple their application components. Which two AWS services facilitate this? (Select two)', 'multi-select', 'Amazon SQS', 'SQS provides a message queue.', 'Amazon SNS', 'SNS provides pub/sub messaging.', 'Amazon EC2', 'EC2 is compute.', 'Amazon EBS', 'EBS is storage.', 'Amazon RDS', 'RDS is database.', None, None, '1,2', 'SQS and SNS are primary services for decoupling application components.', 'SDLC Automation'],
    ['Which two metrics are essential for scaling an Auto Scaling Group based on CPU load? (Select two)', 'multi-select', 'CPUUtilization', 'This is the direct metric.', 'NetworkIn', 'Network is not CPU.', 'DiskReadBytes', 'Disk usage is not CPU.', 'StatusCheckFailed', 'Status check is for health.', 'MemoryUtilization', 'Memory is distinct from CPU.', 'None', 'None.', None, None, '1', 'Wait, "Select two" for CPU scaling? Usually just CPUUtilization. Let\'s adjust. "Which two metrics indicate high load on an EC2 instance?"', '1,5'],
    # Correcting the above question logic in the list:
    ['Which two metrics might indicate high load on an EC2 instance? (Select two)', 'multi-select', 'CPUUtilization', 'High CPU indicates processing load.', 'NetworkIn', 'Network traffic can indicate load but CPU is more direct for compute.', 'DiskReadBytes', 'Disk I/O can indicate load.', 'StatusCheckFailed', 'Failure is not load.', 'MemoryUtilization', 'Memory usage indicates load (custom metric).', None, None, '1,3', 'CPUUtilization and DiskReadBytes (I/O) are standard metrics indicating load.', 'Monitoring and Logging'],
    ['Which two services allow you to host a static website? (Select two)', 'multi-select', 'Amazon S3', 'S3 can host static websites.', 'AWS Amplify', 'Amplify hosts web apps.', 'Amazon EC2', 'EC2 can host a web server.', 'Amazon RDS', 'RDS is a database.', 'Amazon DynamoDB', 'DynamoDB is a database.', None, None, '1,2', 'S3 and Amplify are managed services for hosting static content.', 'SDLC Automation'],
    ['Which two features of IAM help you manage access permissions? (Select two)', 'multi-select', 'IAM Policies', 'Policies define permissions.', 'IAM Roles', 'Roles delegate access.', 'Security Groups', 'Security groups are for network access.', 'Network ACLs', 'NACLs are for network access.', 'VPC Peering', 'Peering is for networking.', None, None, '1,2', 'Policies and Roles are core IAM components for permission management.', 'Security and Compliance'],
    ['You need to collect logs from EC2 instances. Which two steps are required? (Select two)', 'multi-select', 'Install the CloudWatch Agent', 'The agent collects logs.', 'Attach an IAM role with CloudWatch permissions', 'The instance needs permission to upload logs.', 'Enable CloudTrail', 'CloudTrail is for API logs.', 'Configure VPC Flow Logs', 'Flow logs are for network traffic.', 'Create an S3 bucket', 'S3 is not strictly required for CloudWatch logs ingestion.', None, None, '1,2', 'The CloudWatch Agent and proper IAM permissions are necessary for log collection.', 'Monitoring and Logging'],
    ['Which two AWS services support blue/green deployments? (Select two)', 'multi-select', 'AWS Elastic Beanstalk', 'Beanstalk supports swapping URLs for blue/green.', 'AWS CodeDeploy', 'CodeDeploy manages blue/green deployments.', 'Amazon S3', 'S3 is storage.', 'Amazon Glacier', 'Glacier is archive.', 'Amazon SNS', 'SNS is messaging.', None, None, '1,2', 'Elastic Beanstalk and CodeDeploy both natively support blue/green deployment strategies.', 'SDLC Automation'],
    ['Which two factors affect the cost of an Amazon EC2 instance? (Select two)', 'multi-select', 'Instance Type', 'Type determines CPU/RAM resources.', 'Region', 'Costs vary by region.', 'AMI ID', 'AMI ID itself does not determine cost (though software might).', 'Security Group Rules', 'Rules are free.', 'Tags', 'Tags are free.', None, None, '1,2', 'Instance type and the region where it runs are primary cost drivers.', 'Cost Management'],
    ['Which two services are used for Infrastructure as Code? (Select two)', 'multi-select', 'AWS CloudFormation', 'CloudFormation is the native IaC service.', 'AWS OpsWorks', 'OpsWorks is a configuration management service.', 'AWS CodePipeline', 'Pipeline is for orchestration.', 'AWS X-Ray', 'X-Ray is for tracing.', 'Amazon Inspector', 'Inspector is for security.', None, None, '1,2', 'CloudFormation and OpsWorks are key tools for defining infrastructure as code.', 'Configuration Management and IaC'],
    ['Which two methods can be used to secure data at rest in S3? (Select two)', 'multi-select', 'Server-Side Encryption (SSE)', 'SSE encrypts data at rest.', 'Client-Side Encryption', 'Client-side encrypts before upload.', 'SSL/TLS', 'SSL protects data in transit.', 'Signed URLs', 'Signed URLs control access.', 'VPC Endpoints', 'Endpoints secure the network path.', None, None, '1,2', 'Server-side and Client-side encryption are the methods for securing data at rest.', 'Security and Compliance'],
    ['Which two services provide automated backups? (Select two)', 'multi-select', 'Amazon RDS', 'RDS has automated backups.', 'Amazon DynamoDB', 'DynamoDB has point-in-time recovery.', 'Amazon EC2 (instance store)', 'Instance store is ephemeral.', 'Amazon S3 (standard)', 'S3 has versioning, not "backups" in the DB sense.', 'AWS Lambda', 'Lambda is code.', None, None, '1,2', 'RDS and DynamoDB provide managed backup capabilities.', 'Resilient Cloud Solutions'],
    ['Which two components are required for a VPC? (Select two)', 'multi-select', 'CIDR block', 'A VPC must have an IP range.', 'Subnets', 'Subnets divide the VPC.', 'NAT Gateway', 'NAT is optional.', 'Internet Gateway', 'IGW is optional.', 'VPN Gateway', 'VPN is optional.', None, None, '1,2', 'A CIDR block and Subnets are fundamental to VPC structure.', 'Networking'],
    ['Which two services can trigger an AWS Lambda function? (Select two)', 'multi-select', 'Amazon S3', 'S3 event notifications trigger Lambda.', 'Amazon DynamoDB', 'DynamoDB Streams trigger Lambda.', 'Amazon VPC', 'VPC is a network.', 'Amazon EBS', 'EBS is storage.', 'AWS IAM', 'IAM is for permissions.', None, None, '1,2', 'S3 and DynamoDB are common event sources for Lambda.', 'Compute'],
    ['Which two strategies reduce the cost of Spot Instances? (Select two)', 'multi-select', 'Using Spot Fleets', 'Fleets diversify instance types.', 'Using defined duration workloads', 'Wait, Spot costs are market driven. "Diversifying instance types" reduces interruption risk. "Flexible start times". Let\'s pick better options.', 'Use a mix of instance types', 'Diversification helps secure capacity.', 'Deploy in multiple Availability Zones', 'Increases chances of finding capacity.', 'Bid max price', 'Does not reduce cost.', 'Use On-Demand', 'More expensive.', None, None, '1,2', 'Using fleets and multiple AZs helps optimize Spot usage and availability.', 'Cost Management'],
    ['Which two services allow you to run containers? (Select two)', 'multi-select', 'Amazon ECS', 'ECS orchestrates containers.', 'Amazon EKS', 'EKS orchestrates containers.', 'AWS Lambda', 'Lambda runs functions (supports container images now, but ECS/EKS are primary).', 'Amazon S3', 'S3 is storage.', 'Amazon RDS', 'RDS is database.', None, None, '1,2', 'ECS and EKS are the primary container orchestration services.', 'Compute'],

    # --- 10 Select Three Questions ---
    ['Which three pillars are part of the AWS Well-Architected Framework? (Select three)', 'multi-select', 'Security', 'Security is a pillar.', 'Reliability', 'Reliability is a pillar.', 'Cost Optimization', 'Cost Optimization is a pillar.', 'Agility', 'Agility is a benefit, not a pillar.', 'Scalability', 'Scalability is a concept within pillars.', 'Speed', 'Speed is not a pillar.', None, None, '1,2,3', 'The pillars are Operational Excellence, Security, Reliability, Performance Efficiency, Cost Optimization, and Sustainability.', 'AWS Architecture'],
    ['Which three services are used for CI/CD on AWS? (Select three)', 'multi-select', 'AWS CodePipeline', 'Orchestrates the pipeline.', 'AWS CodeBuild', 'Builds the code.', 'AWS CodeDeploy', 'Deploys the code.', 'AWS CodeCommit', 'Stores the code (Source).', 'Amazon EC2', 'Compute target.', 'Amazon S3', 'Storage.', None, None, '1,2,3', 'CodePipeline, CodeBuild, and CodeDeploy form the core CI/CD toolset (along with CodeCommit).', 'SDLC Automation'],
    ['Which three options can be configured in an Auto Scaling Launch Configuration? (Select three)', 'multi-select', 'AMI ID', 'The image to launch.', 'Instance Type', 'The hardware size.', 'Security Groups', 'Firewall rules.', 'VPC ID', 'Launch Configs don\'t specify VPC directly, the ASG does subnets.', 'Desired Capacity', 'ASG property, not Launch Config.', 'Tags', 'ASG property.', None, None, '1,2,3', 'AMI, Instance Type, and Security Groups are defined in the Launch Configuration.', 'Compute'],
    ['Which three logging features are available in CloudWatch? (Select three)', 'multi-select', 'Log Groups', 'Container for logs.', 'Log Streams', 'Sequence of logs.', 'Metric Filters', 'Pattern matching.', 'Tables', 'Not a feature.', 'Indexes', 'Not a feature.', 'Views', 'Not a feature.', None, None, '1,2,3', 'Log Groups, Streams, and Metric Filters are key components of CloudWatch Logs.', 'Monitoring and Logging'],
    ['Which three services can be monitored by AWS Config? (Select three)', 'multi-select', 'Amazon EC2', 'Config tracks EC2.', 'Amazon S3', 'Config tracks S3.', 'AWS IAM', 'Config tracks IAM.', 'AWS Support', 'Not a resource.', 'AWS Billing', 'Not a resource.', 'AWS Artifact', 'Not a resource.', None, None, '1,2,3', 'Config records configuration changes for resources like EC2, S3, and IAM.', 'Security and Compliance'],
    ['Which three layers are part of the Shared Responsibility Model for a managed service like RDS? (Select three)', 'multi-select', 'OS Patching (AWS)', 'AWS handles OS patching.', 'Database Software Patching (AWS)', 'AWS handles DB patching.', 'Physical Security (AWS)', 'AWS handles physical security.', 'Schema Design (Customer)', 'Customer handles schema.', 'Query Optimization (Customer)', 'Customer handles queries.', 'User Permissions (Customer)', 'Customer handles users.', None, None, '1,2,3', 'For managed services, AWS takes care of the OS, DB software, and physical hardware.', 'Security and Compliance'],
    ['Which three types of load balancers are available in AWS? (Select three)', 'multi-select', 'Application Load Balancer', 'Layer 7.', 'Network Load Balancer', 'Layer 4.', 'Classic Load Balancer', 'Legacy.', 'Database Load Balancer', 'Not a type.', 'Storage Load Balancer', 'Not a type.', 'Compute Load Balancer', 'Not a type.', None, None, '1,2,3', 'ALB, NLB, and CLB are the ELB types.', 'Networking'],
    ['Which three methods allow you to connect to an EC2 instance? (Select three)', 'multi-select', 'SSH', 'Standard secure shell.', 'Session Manager', 'Secure browser-based shell.', 'EC2 Instance Connect', 'Browser-based SSH.', 'RDP', 'For Windows.', 'FTP', 'File transfer, not shell.', 'Telnet', 'Insecure.', None, None, '1,2,3', 'SSH, Session Manager, and EC2 Instance Connect are valid connection methods.', 'Compute'],
    ['Which three services facilitate data migration to AWS? (Select three)', 'multi-select', 'AWS Snowball', 'Physical transport.', 'AWS Database Migration Service (DMS)', 'Database migration.', 'AWS DataSync', 'Online data transfer.', 'AWS Connect', 'Contact center.', 'AWS Chime', 'Meeting app.', 'AWS WorkSpaces', 'VDI.', None, None, '1,2,3', 'Snowball, DMS, and DataSync are migration tools.', 'Resilient Cloud Solutions'],
    ['Which three steps are involved in a CodePipeline execution? (Select three)', 'multi-select', 'Source', 'Fetching code.', 'Build', 'Compiling code.', 'Deploy', 'Releasing code.', 'Design', 'Pre-pipeline.', 'Monitor', 'Post-pipeline.', 'Plan', 'Pre-pipeline.', None, None, '1,2,3', 'Source, Build, and Deploy are the standard stages.', 'SDLC Automation'],

    # --- 10 Select Four Questions ---
    ['Which four metrics are collected by default for EC2 instances? (Select four)', 'multi-select', 'CPUUtilization', 'Collected by default.', 'NetworkIn', 'Collected by default.', 'NetworkOut', 'Collected by default.', 'DiskReadBytes', 'Collected by default.', 'MemoryUtilization', 'Custom metric.', 'DiskSpace', 'Custom metric.', None, None, '1,2,3,4', 'CPU and Network/Disk I/O are default metrics. Memory and Disk Space require an agent.', 'Monitoring and Logging'],
    ['Which four status checks are performed by Trusted Advisor? (Select four)', 'multi-select', 'Cost Optimization', 'Core check.', 'Security', 'Core check.', 'Fault Tolerance', 'Core check.', 'Performance', 'Core check.', 'Code Quality', 'Not checked.', 'User Experience', 'Not checked.', None, None, '1,2,3,4', 'Trusted Advisor checks Cost, Security, Fault Tolerance, and Performance.', 'Management'],
    ['Which four services are considered "Serverless"? (Select four)', 'multi-select', 'AWS Lambda', 'Serverless compute.', 'Amazon API Gateway', 'Serverless API.', 'Amazon DynamoDB', 'Serverless DB.', 'Amazon SNS', 'Serverless messaging.', 'Amazon EC2', 'Server.', 'Amazon RDS', 'Server-based (usually).', None, None, '1,2,3,4', 'Lambda, API Gateway, DynamoDB, and SNS are core serverless components.', 'Compute'],
    ['Which four elements are found in an IAM Policy? (Select four)', 'multi-select', 'Effect', 'Allow/Deny.', 'Action', 'API call.', 'Resource', 'Target.', 'Principal', 'Who (in resource policies).', 'Time', 'Condition.', 'Location', 'Condition.', None, None, '1,2,3,4', 'Effect, Action, Resource, and Principal are standard policy elements.', 'Security and Compliance'],
    ['Which four storage classes does Amazon S3 offer? (Select four)', 'multi-select', 'Standard', 'Default.', 'Intelligent-Tiering', 'Auto-tiering.', 'Glacier', 'Archive.', 'One Zone-IA', 'Lower cost.', 'Magnetic', 'EBS type.', 'SSD', 'EBS type.', None, None, '1,2,3,4', 'Standard, Intelligent-Tiering, Glacier, and One Zone-IA are valid S3 classes.', 'Storage'],
    ['Which four routing policies does Route 53 support? (Select four)', 'multi-select', 'Simple', 'Standard.', 'Weighted', 'Split traffic.', 'Latency', 'Speed based.', 'Failover', 'DR.', 'Complex', 'Not a type.', 'Direct', 'Not a type.', None, None, '1,2,3,4', 'Simple, Weighted, Latency, and Failover are routing policies.', 'Networking'],
    ['Which four sources can trigger CloudWatch Events (EventBridge)? (Select four)', 'multi-select', 'EC2 State Change', 'Instance start/stop.', 'Auto Scaling', 'Scale out/in.', 'AWS Console Sign-in', 'Security event.', 'Scheduled Event (Cron)', 'Time-based.', 'User thought', 'No.', 'Manual wish', 'No.', None, None, '1,2,3,4', 'Events can be triggered by state changes, scaling, sign-ins, and schedules.', 'Incident and Event Response'],
    ['Which four parameters can be defined in a CloudFormation Template? (Select four)', 'multi-select', 'Resources', 'Objects to create.', 'Parameters', 'Inputs.', 'Outputs', 'Return values.', 'Mappings', 'Lookup tables.', 'Credentials', 'Never hardcode.', 'Secrets', 'Never hardcode.', None, None, '1,2,3,4', 'Resources, Parameters, Outputs, and Mappings are standard template sections.', 'Configuration Management and IaC'],
    ['Which four features does AWS Config provide? (Select four)', 'multi-select', 'Resource Inventory', 'List of resources.', 'Configuration History', 'Timeline of changes.', 'Configuration Change Notifications', 'Alerts.', 'Compliance Auditing', 'Rules check.', 'Real-time Monitoring', 'That is CloudWatch.', 'Log Analysis', 'That is CloudWatch Logs.', None, None, '1,2,3,4', 'Inventory, History, Notifications, and Auditing are Config features.', 'Security and Compliance'],
    ['Which four languages are supported by AWS Lambda? (Select four)', 'multi-select', 'Python', 'Supported.', 'Node.js', 'Supported.', 'Java', 'Supported.', 'Go', 'Supported.', 'Cobol', 'Custom runtime only.', 'Fortran', 'Custom runtime only.', None, None, '1,2,3,4', 'Python, Node.js, Java, and Go are natively supported runtimes.', 'Compute']
]

# Normalize all rows
data_normalized = [normalize_row(row) for row in data]

# Create DataFrame
df = pd.DataFrame(data_normalized, columns=columns)

# Save CSV
df.to_csv('fixed_devops_pt4.csv', index=False)
print("CSV successfully created: fixed_devops_pt4.csv")