#!/usr/bin/env node
// Resume worker — runs on YOUR machine, not a server.
//
//   node scripts/resume-worker.mjs
//
// Polls resume_requests (service role), and for each queued row:
//   1. reads source PDF / DOCX / text notes
//   2. invokes the active Gemini AI model configured in Admin
//   3. runs resume-maker/scripts/make_resume.sh → .docx + .pdf
//   4. uploads to the private `resumes` bucket and marks the row ready
//
// Prerequisites: node 18+, python3, LibreOffice (soffice).
// Stop with Ctrl+C. Rows stay one of queued/processing/ready/failed.

import { execFileSync, execSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

const env = Object.fromEntries(
  readFileSync(join(ROOT, ".env"), "utf8")
    .split("\n")
    .filter((l) => l.includes("=") && !l.trim().startsWith("#"))
    .map((l) => [
      l.slice(0, l.indexOf("=")).trim(),
      l.slice(l.indexOf("=") + 1).trim().replace(/^["']|["']$/g, ""),
    ])
);

const URL = env.SUPABASE_URL;
const KEY = env.SUPABASE_SERVICE_ROLE_KEY;
if (!URL || !KEY) {
  console.error("Missing SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY in .env");
  process.exit(1);
}
const headers = { apikey: KEY, Authorization: `Bearer ${KEY}` };
const JOBS = join(homedir(), ".yatri-resume-jobs");
mkdirSync(JOBS, { recursive: true });

const SCHEMA = readFileSync(
  join(ROOT, "resume-maker/scripts/resume.example.json"),
  "utf8"
);
const RULES = readFileSync(
  join(ROOT, "resume-maker/references/best_practices.md"),
  "utf8"
);

async function api(path, init = {}) {
  const res = await fetch(`${URL}${path}`, {
    ...init,
    headers: { ...headers, ...(init.headers || {}) },
  });
  if (!res.ok) throw new Error(`${init.method || "GET"} ${path} → ${res.status} ${await res.text()}`);
  return res;
}

/**
 * Fetch the active AI configuration (API key and model) directly from Admin site_settings.
 */
async function getActiveAiConfig() {
  try {
    const res = await api(`/rest/v1/site_settings?key=eq.ai_api_keys`);
    const [row] = await res.json();
    if (Array.isArray(row?.value) && row.value.length > 0) {
      const active = row.value.find((k) => k.isActive) || row.value[0];
      if (active && active.apiKey) {
        return {
          apiKey: active.apiKey,
          model: active.model || "gemini-2.5-flash",
          temperature: active.temperature ?? 0.2,
          maxTokens: active.maxTokens ?? 8192,
        };
      }
    }
  } catch (e) {
    // fallback to legacy setting
  }

  try {
    const res = await api(`/rest/v1/site_settings?key=eq.gemini_ai`);
    const [row] = await res.json();
    if (row?.value?.api_key) {
      return {
        apiKey: row.value.api_key,
        model: row.value.model || "gemini-2.5-flash",
        temperature: row.value.temperature ?? 0.2,
        maxTokens: row.value.max_tokens ?? 8192,
      };
    }
  } catch (e) {}

  return {
    apiKey: env.VITE_GEMINI_API_KEY || "",
    model: "gemini-2.5-flash",
    temperature: 0.2,
    maxTokens: 8192,
  };
}

/**
 * Call the Gemini API with structured multimodal inputs.
 */
async function callGemini(parts, options = {}) {
  const ai = await getActiveAiConfig();
  if (!ai.apiKey) {
    throw new Error("No active AI API key found in Admin Settings (site_settings).");
  }

  const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${ai.model}:generateContent?key=${encodeURIComponent(ai.apiKey)}`;

  const body = {
    contents: [
      {
        parts: parts,
      },
    ],
    generationConfig: {
      temperature: options.temperature ?? ai.temperature ?? 0.1,
      maxOutputTokens: options.maxTokens ?? ai.maxTokens ?? 8192,
      responseMimeType: options.jsonMode ? "application/json" : "text/plain",
    },
  };

  if (options.systemInstruction) {
    body.systemInstruction = {
      parts: [{ text: options.systemInstruction }],
    };
  }

  const res = await fetch(endpoint, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
    signal: AbortSignal.timeout(45000),
  });

  const data = await res.json();

  if (!res.ok) {
    throw new Error(`Gemini API Error: ${data?.error?.message || res.statusText}`);
  }

  const text = data?.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!text) {
    throw new Error("No response generated by Gemini model.");
  }
  return text;
}

async function claimNext() {
  const res = await api(
    `/rest/v1/resume_requests?status=eq.queued&order=created_at.asc&limit=1`
  );
  const [row] = await res.json();
  if (!row) return null;
  const upd = await api(
    `/rest/v1/resume_requests?id=eq.${row.id}&status=eq.queued`,
    {
      method: "PATCH",
      headers: { "Content-Type": "application/json", Prefer: "return=representation" },
      body: JSON.stringify({ status: "processing", updated_at: new Date().toISOString() }),
    }
  );
  const claimed = await upd.json();
  return claimed.length ? claimed[0] : null;
}

async function fetchSourceFile(job, dir) {
  if (!job.input_file_path) return null;
  const res = await api(`/storage/v1/object/resumes/${job.input_file_path}`);
  const buf = Buffer.from(await res.arrayBuffer());
  const isPdf = job.input_file_path.toLowerCase().endsWith(".pdf");
  const local = join(dir, isPdf ? "uploaded-resume.pdf" : "uploaded-resume.docx");
  writeFileSync(local, buf);
  if (isPdf) return "uploaded-resume.pdf";
  // DOCX: extract text with python stdlib
  const py = [
    "import zipfile,re,sys",
    "xml = zipfile.ZipFile(sys.argv[1]).read('word/document.xml').decode('utf-8','ignore')",
    "xml = re.sub(r'</w:p>', chr(10), xml)",
    "print(re.sub(r'<[^>]+>', '', xml))",
  ].join("\n");
  const text = execFileSync("python3", ["-c", py, local], { encoding: "utf8" });
  writeFileSync(join(dir, "uploaded-resume.txt"), text);
  return "uploaded-resume.txt";
}

async function buildJson(job, dir, sourceName) {
  writeFileSync(join(dir, "input.txt"), job.input_text || "");
  writeFileSync(join(dir, "jd.txt"), job.jd_text || "");

  const parts = [];

  // If uploaded PDF exists, send as inline binary to Gemini for native OCR & visual understanding
  if (sourceName === "uploaded-resume.pdf") {
    const pdfBuf = readFileSync(join(dir, "uploaded-resume.pdf"));
    parts.push({
      inline_data: {
        mime_type: "application/pdf",
        data: pdfBuf.toString("base64"),
      },
    });
  } else if (sourceName && existsSync(join(dir, sourceName))) {
    const docText = readFileSync(join(dir, sourceName), "utf8");
    parts.push({ text: `Source resume content:\n${docText}\n` });
  }

  if (job.input_text) {
    parts.push({ text: `Additional user notes/instructions:\n${job.input_text}\n` });
  }

  if (job.jd_text) {
    parts.push({ text: `Target Job Description to tailor toward:\n${job.jd_text}\n` });
  }

  const promptText = `
Candidate Name: ${job.full_name}
Candidate Email: ${job.email || ""}
Output Filename: ${job.full_name.replace(/[^\w ]+/g, "").replace(/ +/g, "_")}_Resume.docx

Instructions:
1. Parse the candidate's career, education, skills, and projects accurately.
2. Mirror honest keywords from the target Job Description (if provided), without fabricating experience.
3. Fit ONE PAGE standard: 3-4 bullets per role, strong action verbs with metrics.
4. Output STRICT JSON conforming to the schema.
`;
  parts.push({ text: promptText });

  const systemInstruction = `You are an elite Senior Executive Resume Architect and technical recruiter.
Distill the candidate's background into a clean, 1-page modern executive resume JSON conforming EXACTLY to this schema:
${SCHEMA}

Quality Guidelines:
${RULES}

CRITICAL RULES:
- Return ONLY a valid JSON object matching the schema.
- NEVER output literal strings "undefined" or "null".
- Omit missing or unknown keys entirely.
- Ensure "skills" is an array of [Category, "Skill1, Skill2, ..."] pairs.
`;

  console.log(`  Invoking Gemini AI model for ${job.full_name}...`);
  const rawJson = await callGemini(parts, {
    systemInstruction,
    jsonMode: true,
    temperature: 0.1,
  });

  writeFileSync(join(dir, "resume.json"), rawJson);
  scrubResumeJson(join(dir, "resume.json"));
}

function scrubResumeJson(path) {
  const clean = (v) => {
    if (v === null || v === undefined) return undefined;
    if (typeof v === "string") {
      const t = v.trim();
      return t === "" || t.toLowerCase() === "undefined" || t.toLowerCase() === "null"
        ? undefined
        : v;
    }
    if (Array.isArray(v)) {
      const arr = v.map(clean).filter((x) => x !== undefined);
      return arr.length ? arr : undefined;
    }
    if (typeof v === "object") {
      const out = {};
      for (const [k, val] of Object.entries(v)) {
        const c = clean(val);
        if (c !== undefined) out[k] = c;
      }
      return Object.keys(out).length ? out : undefined;
    }
    return v;
  };
  const scrubbed = clean(JSON.parse(readFileSync(path, "utf8"))) || {};
  writeFileSync(path, JSON.stringify(scrubbed, null, 2));
}

function buildFiles(job, dir) {
  const outName = job.full_name.replace(/[^\w ]+/g, "").replace(/ +/g, "_") + "_Resume";
  execSync(
    `bash "${join(ROOT, "resume-maker/scripts/make_resume.sh")}" resume.json "${outName}"`,
    { cwd: dir, stdio: "inherit", timeout: 5 * 60 * 1000 }
  );
  const docx = join(dir, `${outName}.docx`);
  const pdf = join(dir, `${outName}.pdf`);
  const find = (p) =>
    existsSync(p)
      ? p
      : existsSync(join(dir, "output", `${outName}${p.endsWith(".pdf") ? ".pdf" : ".docx"}`))
      ? join(dir, "output", `${outName}${p.endsWith(".pdf") ? ".pdf" : ".docx"}`)
      : null;
  return { docx: find(docx), pdf: find(pdf), outName };
}

async function upload(job, localPath, ext, mime) {
  const path = `${job.user_id}/${job.id}/${job.full_name.replace(/[^\w ]+/g, "").replace(/ +/g, "_")}_Resume.${ext}`;
  await api(`/storage/v1/object/resumes/${path}`, {
    method: "POST",
    headers: { "Content-Type": mime, "x-upsert": "true" },
    body: readFileSync(localPath),
  });
  return path;
}

async function finish(id, patch) {
  await api(`/rest/v1/resume_requests?id=eq.${id}`, {
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ ...patch, updated_at: new Date().toISOString() }),
  });
}

function pdfPages(path) {
  try {
    const raw = readFileSync(path).toString("latin1");
    const counts = (raw.match(/\/Count\s+(\d+)/g) || []).map((s) =>
      parseInt(s.replace(/\D+/g, ""), 10)
    );
    if (counts.length) return Math.max(...counts);
    const pageObjs = (raw.match(/\/Type\s*\/Page[^s]/g) || []).length;
    return pageObjs || null;
  } catch {
    return null;
  }
}

async function compactJson(dir, pages) {
  const current = readFileSync(join(dir, "resume.json"), "utf8");
  const prompt = `The following resume produced a ${pages}-page PDF. It must fit EXACTLY ONE page.
Tighten the JSON: set "density":"compact", shorten summary to 2-3 lines, keep at most 3 strong bullets per role, and trim the weakest project or extra section.
Return ONLY the updated valid JSON:
${current}`;

  const compacted = await callGemini([{ text: prompt }], { jsonMode: true, temperature: 0.1 });
  writeFileSync(join(dir, "resume.json"), compacted);
  scrubResumeJson(join(dir, "resume.json"));
}

async function processJob(job) {
  const dir = join(JOBS, job.id);
  mkdirSync(dir, { recursive: true });
  console.log(`▶ ${job.id} — ${job.full_name}`);
  const sourceName = await fetchSourceFile(job, dir);
  await buildJson(job, dir, sourceName);
  let { docx, pdf } = buildFiles(job, dir);
  if (!docx) throw new Error("build produced no .docx");

  // One-page guarantee
  for (let attempt = 0; attempt < 2; attempt++) {
    const pages = pdf ? pdfPages(pdf) : null;
    if (pages === null || pages <= 1) break;
    console.log(`  ${pages} pages — compacting (attempt ${attempt + 1})`);
    await compactJson(dir, pages);
    ({ docx, pdf } = buildFiles(job, dir));
    if (!docx) throw new Error("compaction rebuild produced no .docx");
  }
  const docxPath = await upload(job, docx, "docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document");
  const pdfPath = pdf ? await upload(job, pdf, "pdf", "application/pdf") : null;
  await finish(job.id, { status: "ready", docx_path: docxPath, pdf_path: pdfPath, error: null });
  console.log(`✔ ready — ${docxPath}`);
  await notifyReady(job);
}

async function notifyReady(job) {
  if (!job.email) return;
  try {
    await fetch("https://www.yatricloud.com/api/send-email", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        to: job.email,
        subject: "Your resume is ready · Yatri Cloud",
        html: `<div style="font-family:Arial,sans-serif;max-width:520px;margin:0 auto;padding:24px">
          <h2 style="color:#007CFF;margin:0 0 12px">Your resume is ready, ${job.full_name.split(" ")[0]}!</h2>
          <p>Your polished, one page resume is waiting as Word and PDF.</p>
          <p><a href="https://www.yatricloud.com/resume-maker" style="display:inline-block;background:#007CFF;color:#fff;padding:12px 22px;border-radius:10px;text-decoration:none;font-weight:bold">Download your resume</a></p>
          <p style="color:#666;font-size:13px">It stays private to your Yatri Cloud account.</p>
        </div>`,
      }),
    });
  } catch (err) {
    console.log(`  (ready email skipped: ${err.message})`);
  }
}

// ——— Job matching ————————————————————————————————————————————————————

async function claimNextMatch() {
  const res = await api(
    `/rest/v1/job_match_requests?status=eq.queued&order=created_at.asc&limit=1`
  );
  const [row] = await res.json();
  if (!row) return null;
  const upd = await api(
    `/rest/v1/job_match_requests?id=eq.${row.id}&status=eq.queued`,
    {
      method: "PATCH",
      headers: { "Content-Type": "application/json", Prefer: "return=representation" },
      body: JSON.stringify({ status: "processing", updated_at: new Date().toISOString() }),
    }
  );
  const claimed = await upd.json();
  return claimed.length ? claimed[0] : null;
}

async function finishMatch(id, patch) {
  await api(`/rest/v1/job_match_requests?id=eq.${id}`, {
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ ...patch, updated_at: new Date().toISOString() }),
  });
}

async function processMatch(m) {
  const dir = join(JOBS, `match-${m.id}`);
  mkdirSync(dir, { recursive: true });
  console.log(`▶ match ${m.id}`);

  const res = await api(`/storage/v1/object/resumes/${m.resume_path}`);
  const buf = Buffer.from(await res.arrayBuffer());
  const isPdf = m.resume_path.toLowerCase().endsWith(".pdf");
  const local = join(dir, isPdf ? "resume.pdf" : "resume.docx");
  writeFileSync(local, buf);

  const parts = [];
  if (isPdf) {
    parts.push({
      inline_data: { mime_type: "application/pdf", data: buf.toString("base64") },
    });
  } else {
    const py = [
      "import zipfile,re,sys",
      "xml = zipfile.ZipFile(sys.argv[1]).read('word/document.xml').decode('utf-8','ignore')",
      "xml = re.sub(r'</w:p>', chr(10), xml)",
      "print(re.sub(r'<[^>]+>', '', xml))",
    ].join("\n");
    const txt = execFileSync("python3", ["-c", py, local], { encoding: "utf8" });
    parts.push({ text: `Resume Content:\n${txt}` });
  }

  parts.push({
    text: `Extract candidate roles & keywords in this JSON schema:
{"roles":["3-6 target job titles"], "keywords":["8-14 keywords"], "level":"entry|mid|senior", "summary":"one sentence"}`,
  });

  const rolesText = await callGemini(parts, { jsonMode: true, temperature: 0.1 });
  const roles = JSON.parse(rolesText);

  const kws = (roles.keywords || [])
    .map((k) => String(k).replace(/[^\w +/#.-]+/g, "").trim())
    .filter(Boolean)
    .slice(0, 14);
  const orExpr = kws.map((k) => `title.ilike.*${k}*`).join(",");
  const cand = await api(
    `/rest/v1/job_postings?is_active=eq.true&select=id,title,location,level,remote,job_companies(name)&or=(${encodeURIComponent(orExpr)})&limit=350`
  ).then((r) => r.json());

  if (!cand.length) {
    await finishMatch(m.id, {
      status: "ready",
      result: { ...roles, job_ids: [], total_candidates: 0 },
    });
    console.log(`✔ match ${m.id}: 0 candidates`);
    return;
  }

  const lines = cand
    .slice(0, 300)
    .map((j) => `${j.id}|${j.title}|${j.job_companies?.name || ""}|${j.location}|${j.level}`)
    .join("\n");

  const matchPrompt = `Candidates postings:
${lines}

Candidate Profile:
${JSON.stringify(roles)}

Pick best matching job postings (up to 40). Return JSON: {"job_ids":["..."]}`;

  const matchesText = await callGemini([{ text: matchPrompt }], { jsonMode: true, temperature: 0.1 });
  const matches = JSON.parse(matchesText);
  const valid = new Set(cand.map((j) => j.id));
  const jobIds = (matches.job_ids || []).filter((id) => valid.has(id)).slice(0, 40);

  await finishMatch(m.id, {
    status: "ready",
    result: { ...roles, job_ids: jobIds, total_candidates: cand.length },
  });
  console.log(`✔ match ${m.id}: ${jobIds.length} of ${cand.length} candidates`);
}

// ——— Email drafting ———————————————————————————————————————————————————

async function claimNextEmail() {
  const res = await api(
    `/rest/v1/job_applications?email_status=eq.drafting&order=created_at.asc&limit=1&select=id,job_id,user_id`
  );
  const [row] = await res.json();
  return row || null;
}

async function draftEmail(app) {
  console.log(`▶ email ${app.id}`);
  const [[job], [profile]] = await Promise.all([
    api(`/rest/v1/job_postings?id=eq.${app.job_id}&select=title,description,job_companies(name)`).then((r) => r.json()),
    api(`/rest/v1/job_profiles?user_id=eq.${app.user_id}&select=full_name,roles`).then((r) => r.json()),
  ]);
  const company = job?.job_companies?.name || "the company";

  const brief = `Candidate: ${profile?.full_name || ""}\nTarget roles: ${profile?.roles || ""}\nApplying to: ${job?.title || ""} at ${company}\n\nJob description:\n${(job?.description || "").slice(0, 4000)}`;

  const prompt = `Write a concise, warm, professional cold application email (110-150 words) based on this brief:
${brief}

Return ONLY valid JSON: {"subject":"...","body":"..."}`;

  const emailText = await callGemini([{ text: prompt }], { jsonMode: true, temperature: 0.2 });
  const email = JSON.parse(emailText);

  await api(`/rest/v1/job_applications?id=eq.${app.id}`, {
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      email_subject: String(email.subject || `Application for ${job?.title || "the role"}`).slice(0, 300),
      email_body: String(email.body || ""),
      email_status: "drafted",
    }),
  });
  console.log(`✔ email ${app.id} drafted`);
}

// ——— Main polling loop ————————————————————————————————————————————————

console.log("Yatri resume worker powered by Admin AI Key (Gemini) watching the queue… (Ctrl+C to stop)");
for (;;) {
  try {
    const job = await claimNext();
    if (job) {
      try {
        await processJob(job);
      } catch (err) {
        console.error(`✖ ${job.id}:`, err.message);
        await finish(job.id, {
          status: "failed",
          error: "Build failed: " + err.message,
        });
      }
      continue;
    }
    const match = await claimNextMatch();
    if (match) {
      try {
        await processMatch(match);
      } catch (err) {
        console.error(`✖ match ${match.id}:`, err.message);
        await finishMatch(match.id, {
          status: "failed",
          error: "Matching failed: " + err.message,
        });
      }
      continue;
    }
    const email = await claimNextEmail();
    if (email) {
      try {
        await draftEmail(email);
      } catch (err) {
        console.error(`✖ email ${email.id}:`, err.message);
        await api(`/rest/v1/job_applications?id=eq.${email.id}`, {
          method: "PATCH",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ email_status: "none" }),
        });
      }
      continue;
    }
    await new Promise((r) => setTimeout(r, 5000));
  } catch (err) {
    console.error("worker loop error:", err.message);
    await new Promise((r) => setTimeout(r, 10000));
  }
}
